# Focalboard
# Focalboard is an open source, multilingual, self-hosted project management tool that's an alternative to Trello, Notion, and Asana.
#
# Modifed from official mattermost/focalboard repo
# GitHub: https://github.com/mattermost/focalboard
# 
# Personal version: https://raw.githubusercontent.com/justinKocian/compose-repo/main/Focalboard_docker-compose.yml

version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - 3200:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000

volumes:
  fbdata:
